quant:
    a_qconfig:
        quantizer: LSQFakeQuantize
        observer: MSEObserver
        bit: 8 
        symmetric: False
        ch_axis: -1
    a_qconfig_low:
        quantizer: LSQFakeQuantize
        observer: MSEObserver
        bit: 3
        symmetric: False
        ch_axis: -1
    a_qconfig_med:
        quantizer: LSQFakeQuantize
        observer: MSEObserver
        bit: 4
        symmetric: False
        ch_axis: -1
    a_qconfig_high:
        quantizer: LSQFakeQuantize
        observer: MSEObserver
        bit: 5
        symmetric: False
        ch_axis: -1
    w_qconfig:
        quantizer: AdaRoundFakeQuantize
        observer: MSEObserver
        bit: 2
        symmetric: False
        ch_axis: 0
    calibrate: 1024
    recon:
        batch_size: 32
        scale_lr: 4.0e-5
        warm_up: 0.2
        weight: 0.01
        iters: 2 #20000
        b_range: [20, 2]
        keep_gpu: True
        round_mode: learned_hard_sigmoid
        drop_prob: 0.5
    ptmq:
        lambda1: 0.3333333333333333
        lambda2: 0.3333333333333333
        lambda3: 0.3333333333333333
        mixed_p: 0.5
        gamma1: 100
        gamma2: 100
        gamma3: 100
model:                    # architecture details
    type: resnet18        # model name
    kwargs:
        num_classes: 1000
    path: ./resnet18_weights.pth
data:
    path: C:\Users\d7cho\Downloads\imagenet-mini
    batch_size: 64
    num_workers: 4
    pin_memory: True
    input_size: 224
    test_resize: 256
process:
    seed: 1005
